server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/technical_community?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.pzj.technicalcommunity.model